"""updated table structure

Revision ID: 15db95071e37
Revises: babdb8bcd5a3
Create Date: 2025-12-11 02:33:41.028320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15db95071e37'
down_revision: Union[str, None] = 'babdb8bcd5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. Drop the old Constraint Safely ---
    # We use op.execute with "IF EXISTS" so it doesn't crash if it's already gone.
    op.execute("ALTER TABLE cards DROP CONSTRAINT IF EXISTS cards_series_id_fkey")

    # --- 2. Fix Series Table ---
    # Drop the old ID column
    op.drop_column('series', 'series_id')
    # Make 'name' the new Primary Key
    op.create_primary_key('pk_series', 'series', ['name'])

    # --- 3. Fix Cards Table ---
    # A. Add the new column as Nullable=True first (to prevent crash on existing data)
    op.add_column('cards', sa.Column('series_name', sa.String(), nullable=True))
    
    # B. (Optional) If you have data, you would migrate it here.
    # Since we can't map IDs to Names automatically without a join, we assume
    # you are okay with empty data or will fix it manually. 
    # For now, we update any nulls to a default empty string so we can apply the constraint.
    # UNCOMMENT THE LINE BELOW IF YOU HAVE EXISTING DATA:
    # op.execute("UPDATE cards SET series_name = '' WHERE series_name IS NULL")

    # C. Now make it Non-Nullable
    # (If this fails, it means you have rows where series_name is null)
    op.alter_column('cards', 'series_name', nullable=False)

    # D. Create the NEW Foreign Key linking to series.name
    op.create_foreign_key('fk_cards_series_name', 'cards', 'series', ['series_name'], ['name'])
    
    # E. Finally drop the old column
    op.drop_column('cards', 'series_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('series_id', sa.INTEGER(), server_default=sa.text("nextval('series_series_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('cards', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_series_id_fkey'), 'cards', 'series', ['series_id'], ['series_id'])
    op.drop_column('cards', 'series_name')
    # ### end Alembic commands ###
