"""fixed basses to bases

Revision ID: 39afa544a843
Revises: 1c1c62ad03e6
Create Date: 2025-12-19 14:50:22.415832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39afa544a843'
down_revision: Union[str, None] = '1c1c62ad03e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlb_game_fielding_stats', sa.Column('stolen_bases_allowed', sa.Integer(), nullable=False))
    op.drop_column('mlb_game_fielding_stats', 'stolen_basses_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlb_game_fielding_stats', sa.Column('stolen_basses_allowed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mlb_game_fielding_stats', 'stolen_bases_allowed')
    # ### end Alembic commands ###
