"""

Revision ID: 4c1254c5553b
Revises: b7f4d8a2c1e9
Create Date: 2026-02-11 15:43:56.019414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1254c5553b'
down_revision: Union[str, None] = 'b7f4d8a2c1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cards_year_mlb_id', 'cards', ['year', 'mlb_id'], unique=False)
    op.create_index('ix_cards_year_mlb_id_display_position', 'cards', ['year', 'mlb_id', 'display_position'], unique=False)
    op.create_index('ix_players_last_name', 'players', ['last_name'], unique=False)
    op.create_index('ix_players_last_name_lower', 'players', [sa.literal_column('lower(last_name)')], unique=False)
    op.create_index('ix_players_last_name_no_dot_lower', 'players', [sa.literal_column("lower(replace(last_name, '.', ''))")], unique=False)
    # Keep the existing unique index on show_profiles.username because it is
    # referenced by foreign keys created before the username PK existed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op for show_profiles.username index; we leave the existing unique index intact.
    op.drop_index('ix_players_last_name_no_dot_lower', table_name='players')
    op.drop_index('ix_players_last_name_lower', table_name='players')
    op.drop_index('ix_players_last_name', table_name='players')
    op.drop_index('ix_cards_year_mlb_id_display_position', table_name='cards')
    op.drop_index('ix_cards_year_mlb_id', table_name='cards')
    # ### end Alembic commands ###
