"""

Revision ID: 6df839cb045e
Revises: 7cf3897ffc7b
Create Date: 2026-02-02 20:19:05.716362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df839cb045e'
down_revision: Union[str, None] = '7cf3897ffc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_game_plate_appearances', 'batted_ball_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'putout_code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'k_timing',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'hit_direction',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'error_pos',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_game_plate_appearances', 'error_pos',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'hit_direction',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'k_timing',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'putout_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('show_game_plate_appearances', 'batted_ball_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
