"""

Revision ID: 7cf3897ffc7b
Revises: a0c6881d8a04
Create Date: 2026-02-01 16:36:32.938361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cf3897ffc7b'
down_revision: Union[str, None] = 'a0c6881d8a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_ball_parks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_show_ball_parks_name')
    )
    op.create_index(op.f('ix_show_ball_parks_name'), 'show_ball_parks', ['name'], unique=False)
    op.create_table('show_game_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('home_profile_username', sa.String(length=64), nullable=False),
    sa.Column('away_profile_username', sa.String(length=64), nullable=False),
    sa.Column('home_name', sa.String(length=128), nullable=False),
    sa.Column('away_name', sa.String(length=128), nullable=False),
    sa.Column('home_full_name', sa.String(length=128), nullable=False),
    sa.Column('away_full_name', sa.String(length=128), nullable=False),
    sa.Column('home_result', sa.String(length=1), nullable=False),
    sa.Column('away_result', sa.String(length=1), nullable=False),
    sa.Column('home_runs', sa.SmallInteger(), nullable=False),
    sa.Column('away_runs', sa.SmallInteger(), nullable=False),
    sa.Column('home_hits', sa.SmallInteger(), nullable=False),
    sa.Column('away_hits', sa.SmallInteger(), nullable=False),
    sa.Column('home_errors', sa.SmallInteger(), nullable=False),
    sa.Column('away_errors', sa.SmallInteger(), nullable=False),
    sa.Column('innings', sa.SmallInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ball_park_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('weather_degrees', sa.SmallInteger(), nullable=True),
    sa.Column('weather_description', sa.String(length=64), nullable=True),
    sa.Column('weather_wind', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['away_profile_username'], ['show_profiles.username'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ball_park_id'], ['show_ball_parks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_profile_username'], ['show_profiles.username'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_game_summary_away_profile_username'), 'show_game_summary', ['away_profile_username'], unique=False)
    op.create_index(op.f('ix_show_game_summary_ball_park_id'), 'show_game_summary', ['ball_park_id'], unique=False)
    op.create_index(op.f('ix_show_game_summary_date'), 'show_game_summary', ['date'], unique=False)
    op.create_index(op.f('ix_show_game_summary_home_profile_username'), 'show_game_summary', ['home_profile_username'], unique=False)
    op.create_table('show_batter_boxscore',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('appearance_idx', sa.Integer(), nullable=False),
    sa.Column('replaced_apperance_idx', sa.Integer(), nullable=True),
    sa.Column('player_name_raw', sa.String(length=128), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('sh', sa.Integer(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('gidp', sa.Integer(), nullable=False),
    sa.Column('e', sa.Integer(), nullable=False),
    sa.Column('pb', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('innings', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx')
    )
    op.create_index('ix_show_batter_boxscore_game_side', 'show_batter_boxscore', ['game_id', 'is_home'], unique=False)
    op.create_index(op.f('ix_show_batter_boxscore_mlb_id'), 'show_batter_boxscore', ['mlb_id'], unique=False)
    op.create_table('show_game_half_innings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('inning', sa.SmallInteger(), nullable=False),
    sa.Column('is_home_batting', sa.Boolean(), nullable=False),
    sa.Column('runs', sa.SmallInteger(), nullable=False),
    sa.Column('hits', sa.SmallInteger(), nullable=False),
    sa.Column('walks', sa.SmallInteger(), nullable=False),
    sa.Column('errors', sa.SmallInteger(), nullable=False),
    sa.Column('pitches', sa.SmallInteger(), nullable=False),
    sa.Column('runners_left_on', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'inning', 'is_home_batting', name='uq_half_inning_game_inning_side')
    )
    op.create_index('ix_half_inning_game_inning', 'show_game_half_innings', ['game_id', 'inning'], unique=False)
    op.create_index(op.f('ix_show_game_half_innings_game_id'), 'show_game_half_innings', ['game_id'], unique=False)
    op.create_table('show_game_pitcher_game_scores',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('pitcher_name_raw', sa.String(length=128), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('game_score', sa.Integer(), nullable=False),
    sa.Column('pitcher_mlb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'pitcher_name_raw', 'is_home')
    )
    op.create_index(op.f('ix_show_game_pitcher_game_scores_pitcher_mlb_id'), 'show_game_pitcher_game_scores', ['pitcher_mlb_id'], unique=False)
    op.create_table('show_pitcher_boxscore',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('appearance_idx', sa.SmallInteger(), nullable=False),
    sa.Column('player_name_raw', sa.String(length=128), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('ip_raw', sa.String(length=8), nullable=False),
    sa.Column('outs_pitched', sa.SmallInteger(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('wp', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Integer(), nullable=False),
    sa.Column('save', sa.Integer(), nullable=False),
    sa.Column('b_save', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('s_wins', sa.Integer(), nullable=False),
    sa.Column('s_losses', sa.Integer(), nullable=False),
    sa.Column('s_saves', sa.Integer(), nullable=False),
    sa.Column('s_b_saves', sa.Integer(), nullable=False),
    sa.Column('s_holds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx')
    )
    op.create_index('ix_show_pitcher_boxscore_game_side', 'show_pitcher_boxscore', ['game_id', 'is_home'], unique=False)
    op.create_index(op.f('ix_show_pitcher_boxscore_mlb_id'), 'show_pitcher_boxscore', ['mlb_id'], unique=False)
    op.create_table('show_batter_boxscore_card_candidates',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('appearance_idx', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id', 'is_home', 'appearance_idx'], ['show_batter_boxscore.game_id', 'show_batter_boxscore.is_home', 'show_batter_boxscore.appearance_idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', 'card_id')
    )
    op.create_index('ix_show_batter_boxscore_candidates_card', 'show_batter_boxscore_card_candidates', ['card_id'], unique=False)
    op.create_table('show_game_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('half_inning_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('inning', sa.SmallInteger(), nullable=True),
    sa.Column('is_home_batting', sa.Boolean(), nullable=True),
    sa.Column('outs_before', sa.SmallInteger(), nullable=True),
    sa.Column('outs_after', sa.SmallInteger(), nullable=True),
    sa.Column('home_score_before', sa.SmallInteger(), nullable=True),
    sa.Column('away_score_before', sa.SmallInteger(), nullable=True),
    sa.Column('home_score_after', sa.SmallInteger(), nullable=True),
    sa.Column('away_score_after', sa.SmallInteger(), nullable=True),
    sa.Column('pre_on_1b', sa.Boolean(), nullable=True),
    sa.Column('pre_on_2b', sa.Boolean(), nullable=True),
    sa.Column('pre_on_3b', sa.Boolean(), nullable=True),
    sa.Column('post_on_1b', sa.Boolean(), nullable=True),
    sa.Column('post_on_2b', sa.Boolean(), nullable=True),
    sa.Column('post_on_3b', sa.Boolean(), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('event_text', sa.Text(), nullable=False),
    sa.Column('is_critical_play', sa.Boolean(), nullable=True),
    sa.Column('is_critical_situation', sa.Boolean(), nullable=True),
    sa.Column('is_go_ahead_play', sa.Boolean(), nullable=True),
    sa.Column('is_simulated_play', sa.Boolean(), nullable=True),
    sa.Column('event_seq_in_half', sa.SmallInteger(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['half_inning_id'], ['show_game_half_innings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'seq', name='uq_show_game_events_game_seq')
    )
    op.create_index(op.f('ix_show_game_events_game_id'), 'show_game_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_show_game_events_half_inning_id'), 'show_game_events', ['half_inning_id'], unique=False)
    op.create_index('ix_show_game_events_half_seq', 'show_game_events', ['half_inning_id', 'seq'], unique=False)
    op.create_index('ix_show_game_events_type', 'show_game_events', ['game_id', 'event_type'], unique=False)
    op.create_table('show_pitcher_boxscore_card_candidates',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('appearance_idx', sa.SmallInteger(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id', 'is_home', 'appearance_idx'], ['show_pitcher_boxscore.game_id', 'show_pitcher_boxscore.is_home', 'show_pitcher_boxscore.appearance_idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', 'card_id')
    )
    op.create_index('ix_show_pitcher_boxscore_candidates_card', 'show_pitcher_boxscore_card_candidates', ['card_id'], unique=False)
    op.create_table('show_event_card_candidates',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'role', 'card_id')
    )
    op.create_table('show_event_runner_moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('runner_name_raw', sa.String(length=128), nullable=False),
    sa.Column('runner_mlb_id', sa.Integer(), nullable=True),
    sa.Column('from_base', sa.SmallInteger(), nullable=True),
    sa.Column('to_base', sa.SmallInteger(), nullable=True),
    sa.Column('move_type', sa.String(length=24), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_event_runner_moves_event_id'), 'show_event_runner_moves', ['event_id'], unique=False)
    op.create_index(op.f('ix_show_event_runner_moves_runner_mlb_id'), 'show_event_runner_moves', ['runner_mlb_id'], unique=False)
    op.create_table('show_game_pitching_changes',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_name_raw', sa.String(length=128), nullable=False),
    sa.Column('pitcher_mlb_id', sa.Integer(), nullable=True),
    sa.Column('replaced_pitcher_name_raw', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_show_game_pitching_changes_pitcher_mlb_id'), 'show_game_pitching_changes', ['pitcher_mlb_id'], unique=False)
    op.create_table('show_game_plate_appearances',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('batter_name_raw', sa.String(length=128), nullable=False),
    sa.Column('pitcher_name_raw', sa.String(length=128), nullable=False),
    sa.Column('batter_mlb_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_mlb_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('batted_ball_type', sa.String(length=16), nullable=True),
    sa.Column('fielder_pos', sa.String(length=8), nullable=True),
    sa.Column('putout_code', sa.String(length=16), nullable=True),
    sa.Column('is_out', sa.Boolean(), nullable=True),
    sa.Column('is_double_play', sa.Boolean(), nullable=True),
    sa.Column('is_sac_fly', sa.Boolean(), nullable=True),
    sa.Column('is_sac_bunt', sa.Boolean(), nullable=True),
    sa.Column('runs_scored', sa.SmallInteger(), nullable=True),
    sa.Column('rbi', sa.SmallInteger(), nullable=True),
    sa.Column('hr_distance_ft', sa.SmallInteger(), nullable=True),
    sa.Column('is_perfect_perfect', sa.Boolean(), nullable=True),
    sa.Column('exit_vel_mph', sa.SmallInteger(), nullable=True),
    sa.Column('is_strikeout', sa.Boolean(), nullable=True),
    sa.Column('k_pitch_type', sa.String(length=32), nullable=True),
    sa.Column('k_loc_height', sa.String(length=8), nullable=True),
    sa.Column('k_loc_width', sa.String(length=8), nullable=True),
    sa.Column('k_is_chase', sa.Boolean(), nullable=True),
    sa.Column('k_is_looking', sa.Boolean(), nullable=True),
    sa.Column('k_timing', sa.String(length=16), nullable=True),
    sa.Column('batter_side', sa.String(length=8), nullable=True),
    sa.Column('pitcher_throws', sa.String(length=8), nullable=True),
    sa.Column('is_scoring_play', sa.Boolean(), nullable=True),
    sa.Column('hit_direction', sa.String(length=16), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('error_pos', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_show_game_plate_appearances_batter_mlb_id'), 'show_game_plate_appearances', ['batter_mlb_id'], unique=False)
    op.create_index(op.f('ix_show_game_plate_appearances_pitcher_mlb_id'), 'show_game_plate_appearances', ['pitcher_mlb_id'], unique=False)
    op.create_table('show_game_substitutions',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sub_type', sa.String(length=24), nullable=False),
    sa.Column('incoming_player_name_raw', sa.String(length=128), nullable=False),
    sa.Column('outgoing_player_name_raw', sa.String(length=128), nullable=True),
    sa.Column('incoming_mlb_id', sa.Integer(), nullable=True),
    sa.Column('outgoing_mlb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_show_game_substitutions_incoming_mlb_id'), 'show_game_substitutions', ['incoming_mlb_id'], unique=False)
    op.create_index(op.f('ix_show_game_substitutions_outgoing_mlb_id'), 'show_game_substitutions', ['outgoing_mlb_id'], unique=False)
    op.add_column('show_profile_online_stats', sa.Column('profile_username', sa.String(), nullable=False))
    op.alter_column('show_profile_online_stats', 'year',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='year::integer',
               existing_nullable=False)
    op.drop_constraint(op.f('show_profile_online_stats_profile_id_fkey'), 'show_profile_online_stats', type_='foreignkey')
    op.create_foreign_key(None, 'show_profile_online_stats', 'show_profiles', ['profile_username'], ['username'], ondelete='CASCADE')
    op.drop_column('show_profile_online_stats', 'profile_id')
    op.add_column('show_profiles', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('show_profiles', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('show_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_show_profiles_user_id'), table_name='show_profiles')
    op.create_index(op.f('ix_show_profiles_user_id'), 'show_profiles', ['user_id'], unique=False)
    op.create_index('uq_show_profiles_user_id_not_null', 'show_profiles', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_column('show_profiles', 'id')
    op.drop_column('show_profiles', 'linked_at')
    op.create_primary_key('show_profiles_pkey', 'show_profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_profiles_pkey', 'show_profiles', type_='primary')
    op.add_column('show_profiles', sa.Column('linked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('show_profiles', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_primary_key('show_profiles_pkey', 'show_profiles', ['id'])
    op.drop_index('uq_show_profiles_user_id_not_null', table_name='show_profiles', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index(op.f('ix_show_profiles_user_id'), table_name='show_profiles')
    op.create_index(op.f('ix_show_profiles_user_id'), 'show_profiles', ['user_id'], unique=True)
    op.alter_column('show_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('show_profiles', 'claimed_at')
    op.drop_column('show_profiles', 'first_seen_at')
    op.add_column('show_profile_online_stats', sa.Column('profile_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show_profile_online_stats', type_='foreignkey')
    op.create_foreign_key(op.f('show_profile_online_stats_profile_id_fkey'), 'show_profile_online_stats', 'show_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('show_profile_online_stats', 'year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               postgresql_using='year::varchar',
               existing_nullable=False)
    op.drop_column('show_profile_online_stats', 'profile_username')
    op.drop_index(op.f('ix_show_game_substitutions_outgoing_mlb_id'), table_name='show_game_substitutions')
    op.drop_index(op.f('ix_show_game_substitutions_incoming_mlb_id'), table_name='show_game_substitutions')
    op.drop_table('show_game_substitutions')
    op.drop_index(op.f('ix_show_game_plate_appearances_pitcher_mlb_id'), table_name='show_game_plate_appearances')
    op.drop_index(op.f('ix_show_game_plate_appearances_batter_mlb_id'), table_name='show_game_plate_appearances')
    op.drop_table('show_game_plate_appearances')
    op.drop_index(op.f('ix_show_game_pitching_changes_pitcher_mlb_id'), table_name='show_game_pitching_changes')
    op.drop_table('show_game_pitching_changes')
    op.drop_index(op.f('ix_show_event_runner_moves_runner_mlb_id'), table_name='show_event_runner_moves')
    op.drop_index(op.f('ix_show_event_runner_moves_event_id'), table_name='show_event_runner_moves')
    op.drop_table('show_event_runner_moves')
    op.drop_table('show_event_card_candidates')
    op.drop_index('ix_show_pitcher_boxscore_candidates_card', table_name='show_pitcher_boxscore_card_candidates')
    op.drop_table('show_pitcher_boxscore_card_candidates')
    op.drop_index('ix_show_game_events_type', table_name='show_game_events')
    op.drop_index('ix_show_game_events_half_seq', table_name='show_game_events')
    op.drop_index(op.f('ix_show_game_events_half_inning_id'), table_name='show_game_events')
    op.drop_index(op.f('ix_show_game_events_game_id'), table_name='show_game_events')
    op.drop_table('show_game_events')
    op.drop_index('ix_show_batter_boxscore_candidates_card', table_name='show_batter_boxscore_card_candidates')
    op.drop_table('show_batter_boxscore_card_candidates')
    op.drop_index(op.f('ix_show_pitcher_boxscore_mlb_id'), table_name='show_pitcher_boxscore')
    op.drop_index('ix_show_pitcher_boxscore_game_side', table_name='show_pitcher_boxscore')
    op.drop_table('show_pitcher_boxscore')
    op.drop_index(op.f('ix_show_game_pitcher_game_scores_pitcher_mlb_id'), table_name='show_game_pitcher_game_scores')
    op.drop_table('show_game_pitcher_game_scores')
    op.drop_index(op.f('ix_show_game_half_innings_game_id'), table_name='show_game_half_innings')
    op.drop_index('ix_half_inning_game_inning', table_name='show_game_half_innings')
    op.drop_table('show_game_half_innings')
    op.drop_index(op.f('ix_show_batter_boxscore_mlb_id'), table_name='show_batter_boxscore')
    op.drop_index('ix_show_batter_boxscore_game_side', table_name='show_batter_boxscore')
    op.drop_table('show_batter_boxscore')
    op.drop_index(op.f('ix_show_game_summary_home_profile_username'), table_name='show_game_summary')
    op.drop_index(op.f('ix_show_game_summary_date'), table_name='show_game_summary')
    op.drop_index(op.f('ix_show_game_summary_ball_park_id'), table_name='show_game_summary')
    op.drop_index(op.f('ix_show_game_summary_away_profile_username'), table_name='show_game_summary')
    op.drop_table('show_game_summary')
    op.drop_index(op.f('ix_show_ball_parks_name'), table_name='show_ball_parks')
    op.drop_table('show_ball_parks')
    # ### end Alembic commands ###
