"""

Revision ID: a0c6881d8a04
Revises: c1d9a80b6d35
Create Date: 2026-01-26 19:43:21.750591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c6881d8a04'
down_revision: Union[str, None] = 'c1d9a80b6d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'search_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_cards_search_name_trgm'), table_name='cards', postgresql_ops={'search_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_cards_search_name'), 'cards', ['search_name'], unique=False)
    op.alter_column('users', 'search_display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_search_display_name_trgm'), table_name='users', postgresql_ops={'search_display_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_users_search_display_name'), 'users', ['search_display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_search_display_name'), table_name='users')
    op.create_index(op.f('idx_users_search_display_name_trgm'), 'users', ['search_display_name'], unique=False, postgresql_ops={'search_display_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('users', 'search_display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cards_search_name'), table_name='cards')
    op.create_index(op.f('idx_cards_search_name_trgm'), 'cards', ['search_name'], unique=False, postgresql_ops={'search_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('cards', 'search_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
