"""

Revision ID: a5dbfb597bfc
Revises: 86f6586eb67f
Create Date: 2026-02-04 18:37:27.763337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dbfb597bfc'
down_revision: Union[str, None] = '86f6586eb67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_pitcher_boxscore_candidates_card'), table_name='show_pitcher_boxscore_card_candidates')
    op.drop_table('show_pitcher_boxscore_card_candidates')
    op.drop_index(op.f('ix_show_batter_boxscore_candidates_card'), table_name='show_batter_boxscore_card_candidates')
    op.drop_table('show_batter_boxscore_card_candidates')
    op.drop_index(op.f('ix_show_game_plate_appearances_batter_mlb_id'), table_name='show_game_plate_appearances')
    op.drop_index(op.f('ix_show_game_plate_appearances_pitcher_mlb_id'), table_name='show_game_plate_appearances')
    op.drop_table('show_game_plate_appearances')
    op.drop_index(op.f('ix_show_batter_boxscore_game_side'), table_name='show_batter_boxscore')
    op.drop_index(op.f('ix_show_batter_boxscore_mlb_id'), table_name='show_batter_boxscore')
    op.drop_table('show_batter_boxscore')
    op.drop_table('show_event_card_candidates')
    op.drop_index(op.f('ix_show_game_substitutions_incoming_mlb_id'), table_name='show_game_substitutions')
    op.drop_index(op.f('ix_show_game_substitutions_outgoing_mlb_id'), table_name='show_game_substitutions')
    op.drop_table('show_game_substitutions')
    op.drop_index(op.f('ix_show_game_pitcher_game_scores_pitcher_mlb_id'), table_name='show_game_pitcher_game_scores')
    op.drop_table('show_game_pitcher_game_scores')
    op.drop_index(op.f('ix_show_pitcher_boxscore_game_side'), table_name='show_pitcher_boxscore')
    op.drop_index(op.f('ix_show_pitcher_boxscore_mlb_id'), table_name='show_pitcher_boxscore')
    op.drop_table('show_pitcher_boxscore')
    op.drop_index(op.f('ix_show_event_runner_moves_event_id'), table_name='show_event_runner_moves')
    op.drop_index(op.f('ix_show_event_runner_moves_runner_mlb_id'), table_name='show_event_runner_moves')
    op.drop_table('show_event_runner_moves')
    op.drop_index(op.f('ix_show_game_pitching_changes_pitcher_mlb_id'), table_name='show_game_pitching_changes')
    op.drop_table('show_game_pitching_changes')
    op.drop_index(op.f('ix_show_game_events_game_id'), table_name='show_game_events')
    op.drop_index(op.f('ix_show_game_events_half_inning_id'), table_name='show_game_events')
    op.drop_index(op.f('ix_show_game_events_half_seq'), table_name='show_game_events')
    op.drop_index(op.f('ix_show_game_events_type'), table_name='show_game_events')
    op.drop_table('show_game_events')
    op.drop_index(op.f('ix_half_inning_game_inning'), table_name='show_game_half_innings')
    op.drop_index(op.f('ix_show_game_half_innings_game_id'), table_name='show_game_half_innings')
    op.drop_table('show_game_half_innings')
    # Keep the existing unique index on show_profiles.username because it is
    # referenced by foreign keys created before the username PK existed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op for show_profiles.username index; we leave the existing unique index intact.
    op.create_table('show_game_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('show_game_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('half_inning_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inning', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_home_batting', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('outs_before', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('outs_after', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('home_score_before', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('away_score_before', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('home_score_after', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('away_score_after', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('pre_on_1b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pre_on_2b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pre_on_3b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('post_on_1b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('post_on_2b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('post_on_3b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('event_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_critical_play', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_critical_situation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_go_ahead_play', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_simulated_play', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('event_seq_in_half', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('parser_version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], name='show_game_events_game_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['half_inning_id'], ['show_game_half_innings.id'], name='show_game_events_half_inning_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='show_game_events_pkey'),
    sa.UniqueConstraint('game_id', 'seq', name='uq_show_game_events_game_seq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_show_game_events_type'), 'show_game_events', ['game_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_show_game_events_half_seq'), 'show_game_events', ['half_inning_id', 'seq'], unique=False)
    op.create_index(op.f('ix_show_game_events_half_inning_id'), 'show_game_events', ['half_inning_id'], unique=False)
    op.create_index(op.f('ix_show_game_events_game_id'), 'show_game_events', ['game_id'], unique=False)
    op.create_table('show_game_pitching_changes',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pitcher_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('pitcher_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('replaced_pitcher_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], name=op.f('show_game_pitching_changes_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('show_game_pitching_changes_pkey'))
    )
    op.create_index(op.f('ix_show_game_pitching_changes_pitcher_mlb_id'), 'show_game_pitching_changes', ['pitcher_mlb_id'], unique=False)
    op.create_table('show_event_runner_moves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('runner_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('runner_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_base', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('to_base', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('move_type', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], name=op.f('show_event_runner_moves_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('show_event_runner_moves_pkey'))
    )
    op.create_index(op.f('ix_show_event_runner_moves_runner_mlb_id'), 'show_event_runner_moves', ['runner_mlb_id'], unique=False)
    op.create_index(op.f('ix_show_event_runner_moves_event_id'), 'show_event_runner_moves', ['event_id'], unique=False)
    op.create_table('show_pitcher_boxscore',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('appearance_idx', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('player_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_raw', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('outs_pitched', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('r', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('h', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('er', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bb', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('so', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('era', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loss', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('save', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('b_save', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_losses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_saves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_b_saves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_holds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], name='show_pitcher_boxscore_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', name='show_pitcher_boxscore_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_show_pitcher_boxscore_mlb_id'), 'show_pitcher_boxscore', ['mlb_id'], unique=False)
    op.create_index(op.f('ix_show_pitcher_boxscore_game_side'), 'show_pitcher_boxscore', ['game_id', 'is_home'], unique=False)
    op.create_table('show_game_pitcher_game_scores',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pitcher_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('game_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pitcher_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], name=op.f('show_game_pitcher_game_scores_game_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'pitcher_name_raw', 'is_home', name=op.f('show_game_pitcher_game_scores_pkey'))
    )
    op.create_index(op.f('ix_show_game_pitcher_game_scores_pitcher_mlb_id'), 'show_game_pitcher_game_scores', ['pitcher_mlb_id'], unique=False)
    op.create_table('show_game_substitutions',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_type', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('incoming_player_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('outgoing_player_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('incoming_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outgoing_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], name=op.f('show_game_substitutions_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('show_game_substitutions_pkey'))
    )
    op.create_index(op.f('ix_show_game_substitutions_outgoing_mlb_id'), 'show_game_substitutions', ['outgoing_mlb_id'], unique=False)
    op.create_index(op.f('ix_show_game_substitutions_incoming_mlb_id'), 'show_game_substitutions', ['incoming_mlb_id'], unique=False)
    op.create_table('show_event_card_candidates',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('show_event_card_candidates_card_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], name=op.f('show_event_card_candidates_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'role', 'card_id', name=op.f('show_event_card_candidates_pkey'))
    )
    op.create_table('show_batter_boxscore',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('appearance_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replaced_apperance_idx', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ab', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('h', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('r', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rbi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bb', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('so', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doubles', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('triples', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hr', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sh', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sf', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gidp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('e', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pb', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hbp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sb', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('innings', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], name='show_batter_boxscore_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', name='show_batter_boxscore_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_show_batter_boxscore_mlb_id'), 'show_batter_boxscore', ['mlb_id'], unique=False)
    op.create_index(op.f('ix_show_batter_boxscore_game_side'), 'show_batter_boxscore', ['game_id', 'is_home'], unique=False)
    op.create_table('show_game_plate_appearances',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batter_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('pitcher_name_raw', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('batter_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitcher_mlb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('batted_ball_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('fielder_pos', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('putout_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('is_out', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_double_play', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_sac_fly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_sac_bunt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('runs_scored', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rbi', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hr_distance_ft', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_perfect_perfect', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exit_vel_mph', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_strikeout', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('k_pitch_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('k_loc_height', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('k_loc_width', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('k_is_chase', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('k_is_looking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('k_timing', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('batter_side', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('pitcher_throws', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('is_scoring_play', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hit_direction', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('is_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_pos', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['show_game_events.id'], name=op.f('show_game_plate_appearances_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('show_game_plate_appearances_pkey'))
    )
    op.create_index(op.f('ix_show_game_plate_appearances_pitcher_mlb_id'), 'show_game_plate_appearances', ['pitcher_mlb_id'], unique=False)
    op.create_index(op.f('ix_show_game_plate_appearances_batter_mlb_id'), 'show_game_plate_appearances', ['batter_mlb_id'], unique=False)
    op.create_table('show_game_half_innings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inning', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('is_home_batting', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('runs', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('hits', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('walks', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('errors', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('pitches', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('runners_left_on', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['show_game_summary.id'], name=op.f('show_game_half_innings_game_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('show_game_half_innings_pkey')),
    sa.UniqueConstraint('game_id', 'inning', 'is_home_batting', name=op.f('uq_half_inning_game_inning_side'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_show_game_half_innings_game_id'), 'show_game_half_innings', ['game_id'], unique=False)
    op.create_index(op.f('ix_half_inning_game_inning'), 'show_game_half_innings', ['game_id', 'inning'], unique=False)
    op.create_table('show_batter_boxscore_card_candidates',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('appearance_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('show_batter_boxscore_card_candidates_card_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id', 'is_home', 'appearance_idx'], ['show_batter_boxscore.game_id', 'show_batter_boxscore.is_home', 'show_batter_boxscore.appearance_idx'], name=op.f('show_batter_boxscore_card_can_game_id_is_home_appearance_i_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', 'card_id', name=op.f('show_batter_boxscore_card_candidates_pkey'))
    )
    op.create_index(op.f('ix_show_batter_boxscore_candidates_card'), 'show_batter_boxscore_card_candidates', ['card_id'], unique=False)
    op.create_table('show_pitcher_boxscore_card_candidates',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('appearance_idx', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('show_pitcher_boxscore_card_candidates_card_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id', 'is_home', 'appearance_idx'], ['show_pitcher_boxscore.game_id', 'show_pitcher_boxscore.is_home', 'show_pitcher_boxscore.appearance_idx'], name=op.f('show_pitcher_boxscore_card_ca_game_id_is_home_appearance_i_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'is_home', 'appearance_idx', 'card_id', name=op.f('show_pitcher_boxscore_card_candidates_pkey'))
    )
    op.create_index(op.f('ix_show_pitcher_boxscore_candidates_card'), 'show_pitcher_boxscore_card_candidates', ['card_id'], unique=False)
    # ### end Alembic commands ###
