"""add users table

Revision ID: d42ed8c93a64
Revises: a61d8287b03a
Create Date: 2026-01-17 21:39:04.865492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42ed8c93a64'
down_revision: Union[str, None] = 'a61d8287b03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_id')
    )
    op.drop_constraint(op.f('card_locations_card_id_fkey'), 'card_locations', type_='foreignkey')
    op.create_foreign_key(None, 'card_locations', 'cards', ['card_id'], ['id'])
    op.drop_constraint(op.f('card_quirks_card_id_fkey'), 'card_quirks', type_='foreignkey')
    op.create_foreign_key(None, 'card_quirks', 'cards', ['card_id'], ['id'])
    op.drop_constraint(op.f('card_updates_card_id_fkey'), 'card_updates', type_='foreignkey')
    op.create_foreign_key(None, 'card_updates', 'cards', ['card_id'], ['id'])
    op.alter_column('cards', 'source_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('listings_card_id_fkey'), 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'cards', ['card_id'], ['id'])
    op.drop_constraint(op.f('pitches_card_id_fkey'), 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key(op.f('pitches_card_id_fkey'), 'pitches', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key(op.f('listings_card_id_fkey'), 'listings', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cards', 'source_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'card_updates', type_='foreignkey')
    op.create_foreign_key(op.f('card_updates_card_id_fkey'), 'card_updates', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'card_quirks', type_='foreignkey')
    op.create_foreign_key(op.f('card_quirks_card_id_fkey'), 'card_quirks', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'card_locations', type_='foreignkey')
    op.create_foreign_key(op.f('card_locations_card_id_fkey'), 'card_locations', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_table('users')
    # ### end Alembic commands ###
