"""

Revision ID: e653c37678ce
Revises: d42ed8c93a64
Create Date: 2026-01-26 16:12:54.554472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e653c37678ce'
down_revision: Union[str, None] = 'd42ed8c93a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("scope in ('standard','fielding')", name='ck_prediction_runs_scope'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_runs_run_at'), 'prediction_runs', ['run_at'], unique=False)
    op.create_table('update_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_update_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_schedule_next_update_at'), 'update_schedule', ['next_update_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolios_user_name')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('show_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_level', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('nameplate_equipped', sa.String(), nullable=True),
    sa.Column('icon_equipped', sa.String(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_profiles_user_id'), 'show_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_show_profiles_username'), 'show_profiles', ['username'], unique=True)
    op.create_table('user_update_scores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('points_total', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['update_id', 'update_date'], ['roster_updates.id', 'roster_updates.date'], name='fk_user_update_scores_roster_update', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'update_id', 'update_date')
    )
    op.create_index('ix_user_update_scores_user_recent', 'user_update_scores', ['user_id', 'computed_at'], unique=False)
    op.create_table('show_profile_online_stats',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('runs_per_game', sa.Float(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Float(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['show_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'year')
    )
    op.create_table('card_predictions',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('predicted_ovr', sa.Integer(), nullable=True),
    sa.Column('predicted_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_rarity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['prediction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'card_id')
    )
    op.create_index('ix_card_predictions_card_run_desc', 'card_predictions', ['card_id', 'run_id'], unique=False)
    op.create_table('card_vote_aggregates',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('count_total', sa.Integer(), nullable=False),
    sa.Column('sum_votes', sa.Integer(), nullable=False),
    sa.Column('count_pos', sa.Integer(), nullable=False),
    sa.Column('count_neg', sa.Integer(), nullable=False),
    sa.Column('count_zero', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_id', 'update_date'], ['roster_updates.id', 'roster_updates.date'], name='fk_card_vote_aggs_roster_update', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('update_id', 'update_date', 'card_id')
    )
    op.create_index('ix_card_vote_aggs_update_card', 'card_vote_aggregates', ['update_id', 'update_date', 'card_id'], unique=False)
    op.create_table('card_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('vote_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('vote_value >= -100 AND vote_value <= 100', name='ck_card_votes_vote_value'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_id', 'update_date'], ['roster_updates.id', 'roster_updates.date'], name='fk_card_votes_roster_update', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'update_id', 'update_date', name='uq_card_votes_unique_vote')
    )
    op.create_index(op.f('ix_card_votes_card_id'), 'card_votes', ['card_id'], unique=False)
    op.create_index('ix_card_votes_update_card', 'card_votes', ['update_id', 'update_date', 'card_id'], unique=False)
    op.create_index(op.f('ix_card_votes_user_id'), 'card_votes', ['user_id'], unique=False)
    op.create_index('ix_card_votes_user_update', 'card_votes', ['user_id', 'update_id', 'update_date'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('user_predicted_ovr', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'card_id')
    )
    op.create_index('ix_portfolio_holdings_card', 'portfolio_holdings', ['card_id'], unique=False)
    op.create_index('ix_portfolio_holdings_portfolio', 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_transactions_card_id'), 'portfolio_transactions', ['card_id'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_occurred_at'), 'portfolio_transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_portfolio_id'), 'portfolio_transactions', ['portfolio_id'], unique=False)
    op.create_table('vote_results',
    sa.Column('vote_id', sa.BigInteger(), nullable=False),
    sa.Column('did_update', sa.Boolean(), nullable=False),
    sa.Column('actual_old_ovr', sa.Integer(), nullable=True),
    sa.Column('actual_new_ovr', sa.Integer(), nullable=True),
    sa.Column('actual_delta_ovr', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['card_votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_results')
    op.drop_index(op.f('ix_portfolio_transactions_portfolio_id'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_occurred_at'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_card_id'), table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index('ix_portfolio_holdings_portfolio', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_card', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index('ix_card_votes_user_update', table_name='card_votes')
    op.drop_index(op.f('ix_card_votes_user_id'), table_name='card_votes')
    op.drop_index('ix_card_votes_update_card', table_name='card_votes')
    op.drop_index(op.f('ix_card_votes_card_id'), table_name='card_votes')
    op.drop_table('card_votes')
    op.drop_index('ix_card_vote_aggs_update_card', table_name='card_vote_aggregates')
    op.drop_table('card_vote_aggregates')
    op.drop_index('ix_card_predictions_card_run_desc', table_name='card_predictions')
    op.drop_table('card_predictions')
    op.drop_table('show_profile_online_stats')
    op.drop_index('ix_user_update_scores_user_recent', table_name='user_update_scores')
    op.drop_table('user_update_scores')
    op.drop_index(op.f('ix_show_profiles_username'), table_name='show_profiles')
    op.drop_index(op.f('ix_show_profiles_user_id'), table_name='show_profiles')
    op.drop_table('show_profiles')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_update_schedule_next_update_at'), table_name='update_schedule')
    op.drop_table('update_schedule')
    op.drop_index(op.f('ix_prediction_runs_run_at'), table_name='prediction_runs')
    op.drop_table('prediction_runs')
    # ### end Alembic commands ###
