[pytest]
testpaths = tests
python_files = test_*.py
addopts = --cov=shared.queue --cov=apps.scheduler --cov=apps.jobs.main --cov=apps.jobs.router --cov=apps.jobs.job --cov=apps.jobs.card_sync --cov=apps.jobs.market_sync --cov=apps.jobs.market_candle_sync --cov=apps.jobs.roster_update_sync --cov=apps.jobs.game_boxscore_sync --cov=apps.jobs.player_sync --cov=apps.jobs.prediction_sync --cov-report=term-missing --cov-report=xml:tests/coverage/coverage.xml --cov-report=html:tests/coverage/html
