services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build: 
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /app
    image: mlb_backend_image
    restart: unless-stopped
    volumes:
      - ../../apps/backend/src:/app/src
      - ../../apps/backend/alembic:/app/alembic
      - ../../apps/backend/alembic.ini:/app/alembic.ini
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH}
      TZ: America/Vancouver
    depends_on:
      - db
    networks:
      - app_network
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    secrets:
      - firebase_service_key

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  portainer_data:

secrets:
  firebase_service_key:
    file: ../../secrets/firebase_service_key.json