"""added caught_stealing

Revision ID: 1c1c62ad03e6
Revises: 93b890ade78b
Create Date: 2025-12-19 14:47:12.606823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1c62ad03e6'
down_revision: Union[str, None] = '93b890ade78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlb_game_fielding_stats', sa.Column('stolen_basses_allowed', sa.Integer(), nullable=False))
    op.add_column('mlb_game_fielding_stats', sa.Column('caught_stealing', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlb_game_fielding_stats', 'caught_stealing')
    op.drop_column('mlb_game_fielding_stats', 'stolen_basses_allowed')
    # ### end Alembic commands ###
