"""Nullable fields bug

Revision ID: 9c5a80848b23
Revises: ce3ed2969a42
Create Date: 2025-12-16 01:16:58.904596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5a80848b23'
down_revision: Union[str, None] = 'ce3ed2969a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'is_sellable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'has_augment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'has_rank_change',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'event',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'ui_anim_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'ui_anim_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'event',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'has_rank_change',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'has_augment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'is_sellable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
