"""Initial migration

Revision ID: babdb8bcd5a3
Revises: 
Create Date: 2025-12-07 13:37:12.395400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babdb8bcd5a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('mlb_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlb_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quirks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roster_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('is_fielding', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('mlb_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['mlb_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('birth_location_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('boxscore_name', sa.String(), nullable=False),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('mlb_debut_date', sa.Date(), nullable=True),
    sa.Column('bat_side_code', sa.String(), nullable=False),
    sa.Column('pitch_hand_code', sa.String(), nullable=False),
    sa.Column('strike_zone_top', sa.String(), nullable=False),
    sa.Column('strike_zone_bottom', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['birth_location_id'], ['birth_locations.id'], ),
    sa.ForeignKeyConstraint(['current_team_id'], ['mlb_teams.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['mlb_positions.id'], ),
    sa.PrimaryKeyConstraint('mlb_id')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('baked_img', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('team_short_name', sa.String(), nullable=False),
    sa.Column('ovr', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('display_position', sa.String(), nullable=False),
    sa.Column('display_secondary_positions', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bat_hand', sa.String(), nullable=False),
    sa.Column('throw_hand', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('born', sa.String(), nullable=False),
    sa.Column('is_hitter', sa.Boolean(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('pitching_clutch', sa.Integer(), nullable=False),
    sa.Column('hits_per_bf', sa.Integer(), nullable=False),
    sa.Column('k_per_bf', sa.Integer(), nullable=False),
    sa.Column('bb_per_bf', sa.Integer(), nullable=False),
    sa.Column('hr_per_bf', sa.Integer(), nullable=False),
    sa.Column('pitch_velocity', sa.Integer(), nullable=False),
    sa.Column('pitch_control', sa.Integer(), nullable=False),
    sa.Column('pitch_movement', sa.Integer(), nullable=False),
    sa.Column('contact_left', sa.Integer(), nullable=False),
    sa.Column('contact_right', sa.Integer(), nullable=False),
    sa.Column('power_left', sa.Integer(), nullable=False),
    sa.Column('power_right', sa.Integer(), nullable=False),
    sa.Column('plate_vision', sa.Integer(), nullable=False),
    sa.Column('plate_discipline', sa.Integer(), nullable=False),
    sa.Column('batting_clutch', sa.Integer(), nullable=False),
    sa.Column('bunting_ability', sa.Integer(), nullable=False),
    sa.Column('drag_bunting_ability', sa.Integer(), nullable=False),
    sa.Column('hitting_durability', sa.Integer(), nullable=False),
    sa.Column('fielding_durability', sa.Integer(), nullable=False),
    sa.Column('fielding_ability', sa.Integer(), nullable=False),
    sa.Column('arm_strength', sa.Integer(), nullable=False),
    sa.Column('arm_accuracy', sa.Integer(), nullable=False),
    sa.Column('reaction_time', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('baserunning_ability', sa.Integer(), nullable=False),
    sa.Column('baserunning_aggression', sa.Integer(), nullable=False),
    sa.Column('hit_rank_image', sa.String(), nullable=True),
    sa.Column('fielding_rank_image', sa.String(), nullable=True),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('has_augment', sa.Boolean(), nullable=False),
    sa.Column('augment_text', sa.String(), nullable=True),
    sa.Column('augment_end_date', sa.Date(), nullable=True),
    sa.Column('has_matchup', sa.Boolean(), nullable=False),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('new_rank', sa.Integer(), nullable=False),
    sa.Column('has_rank_change', sa.Boolean(), nullable=False),
    sa.Column('event', sa.Boolean(), nullable=False),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.Column('is_live_set', sa.Boolean(), nullable=False),
    sa.Column('ui_anim_index', sa.Integer(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mlb_id'], ['players.mlb_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('achievement_value', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('stat_desc', sa.String(), nullable=False),
    sa.Column('stat_abbrev', sa.String(), nullable=False),
    sa.Column('stat_difference', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mlb_id'], ['players.mlb_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlb_game_boxscores',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('card_locations',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['location_name'], ['locations.name'], ),
    sa.PrimaryKeyConstraint('card_id', 'location_name')
    )
    op.create_table('card_quirks',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quirk_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['quirk_name'], ['quirks.name'], ),
    sa.PrimaryKeyConstraint('card_id', 'quirk_name')
    )
    op.create_table('card_updates',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('new_ovr', sa.Integer(), nullable=False),
    sa.Column('new_rarity', sa.String(), nullable=False),
    sa.Column('old_ovr', sa.Integer(), nullable=False),
    sa.Column('old_rarity', sa.String(), nullable=False),
    sa.Column('trend_display', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['roster_updates.id'], ),
    sa.PrimaryKeyConstraint('update_id', 'card_id')
    )
    op.create_table('listings',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('best_sell_price', sa.Integer(), nullable=True),
    sa.Column('best_buy_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('mlb_game_baserunning_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('caught_stealing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'player_id'], ['mlb_game_boxscores.game_id', 'mlb_game_boxscores.player_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('mlb_game_batting_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('tb', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('intentional_walks', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('flyOuts', sa.Integer(), nullable=False),
    sa.Column('groundOuts', sa.Integer(), nullable=False),
    sa.Column('airOuts', sa.Integer(), nullable=False),
    sa.Column('gidp', sa.Integer(), nullable=False),
    sa.Column('gitp', sa.Integer(), nullable=False),
    sa.Column('lob', sa.Integer(), nullable=False),
    sa.Column('sac_bunts', sa.Integer(), nullable=False),
    sa.Column('sac_flies', sa.Integer(), nullable=False),
    sa.Column('pop_outs', sa.Integer(), nullable=False),
    sa.Column('line_outs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'player_id'], ['mlb_game_boxscores.game_id', 'mlb_game_boxscores.player_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id', 'split')
    )
    op.create_table('mlb_game_fielding_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('put_outs', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('chances', sa.Integer(), nullable=False),
    sa.Column('passed_balls', sa.Integer(), nullable=False),
    sa.Column('pickoffs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'player_id'], ['mlb_game_boxscores.game_id', 'mlb_game_boxscores.player_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('mlb_game_pitching_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('outs_pitched', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Float(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('pitches_thrown', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('intentional_walks', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('save_opportunities', sa.Integer(), nullable=False),
    sa.Column('holds', sa.Integer(), nullable=False),
    sa.Column('blown_saves', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('batters_faced', sa.Integer(), nullable=False),
    sa.Column('balls_thrown', sa.Integer(), nullable=False),
    sa.Column('strikes_thrown', sa.Integer(), nullable=False),
    sa.Column('balks', sa.Integer(), nullable=False),
    sa.Column('wild_pitches', sa.Integer(), nullable=False),
    sa.Column('inherited_runners', sa.Integer(), nullable=False),
    sa.Column('inherited_runners_scored', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'player_id'], ['mlb_game_boxscores.game_id', 'mlb_game_boxscores.player_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id', 'split')
    )
    op.create_table('pitches',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('control', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'name')
    )
    op.create_table('card_attribute_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('delta', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['update_id', 'card_id'], ['card_updates.update_id', 'card_updates.card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completed_orders',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_buy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['listings.card_id'], ),
    sa.PrimaryKeyConstraint('card_id', 'date')
    )
    op.create_table('market_candles',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('open_buy_price', sa.Integer(), nullable=False),
    sa.Column('open_sell_price', sa.Integer(), nullable=False),
    sa.Column('low_buy_price', sa.Integer(), nullable=False),
    sa.Column('low_sell_price', sa.Integer(), nullable=False),
    sa.Column('high_buy_price', sa.Integer(), nullable=False),
    sa.Column('high_sell_price', sa.Integer(), nullable=False),
    sa.Column('close_buy_price', sa.Integer(), nullable=False),
    sa.Column('close_sell_price', sa.Integer(), nullable=False),
    sa.Column('sell_volume', sa.Integer(), nullable=False),
    sa.Column('buy_volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['listings.card_id'], ),
    sa.PrimaryKeyConstraint('card_id', 'start_time')
    )
    op.create_table('price_history',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('best_buy_price', sa.Integer(), nullable=True),
    sa.Column('best_sell_price', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['listings.card_id'], ),
    sa.PrimaryKeyConstraint('card_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('market_candles')
    op.drop_table('completed_orders')
    op.drop_table('card_attribute_changes')
    op.drop_table('pitches')
    op.drop_table('mlb_game_pitching_stats')
    op.drop_table('mlb_game_fielding_stats')
    op.drop_table('mlb_game_batting_stats')
    op.drop_table('mlb_game_baserunning_stats')
    op.drop_table('listings')
    op.drop_table('card_updates')
    op.drop_table('card_quirks')
    op.drop_table('card_locations')
    op.drop_table('mlb_game_boxscores')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('players')
    op.drop_table('mlb_games')
    op.drop_table('series')
    op.drop_table('roster_updates')
    op.drop_table('quirks')
    op.drop_table('mlb_teams')
    op.drop_table('mlb_positions')
    op.drop_table('locations')
    op.drop_table('birth_locations')
    # ### end Alembic commands ###
